###########
# site.title
title: Cookieblues
description: Personal blog
url: https://cookieblues.github.io


#########################
# more settings
markdown: kramdown
kramdown:
  math_engine: mathjax

sass:
  sass_dir: css
  style:    compressed

permalink: /:title/
timezone: America/New_York
future: false

exclude:
- README.md
- LICENSE.md
