PARTIES = {
    "other": {"name": "other", "letter": "NA", "color": "black"},
    "unanswered": {"name": "unanswered", "letter": "NA", "color": "grey"},
    "Socialdemokratiet": {"name": "Socialdemokratiet", "letter": "S", "color": "#c9002c"},
    "Radikale Venstre": {"name": "Radikale Venstre", "letter": "B", "color": "#d2307e"},
    "Det Konservative Folkeparti": {"name": "Det Konservative Folkeparti", "letter": "K", "color": "#00583C"},
    "Nye Borgerlige": {"name": "Nye Borgerlige", "letter": "D", "color": "#004450"},
    "Socialistisk Folkeparti": {"name": "Socialistisk Folkeparti", "letter": "F", "color": "#C52E26"},
    "Enhedslisten": {"name": "Enhedslisten", "letter": "Ø", "color": "#D0004D"},
    "Liberal Alliance": {"name": "Liberal Alliance", "letter": "I", "color": "#0A1B3E"},
    "Kristendemokraterne": {"name": "Kristendemokraterne", "letter": "K", "color": "#6070b6"},
    "Dansk Folkeparti": {"name": "Dansk Folkeparti", "letter": "O", "color": "#FFFF00"},
    "Venstre": {"name": "Venstre", "letter": "V", "color": "#01278e"},
    "Borgernes Parti": {"name": "Borgernes Parti", "letter": "H", "color": "#2b72fe"},
    "Moderaterne": {"name": "Moderaterne", "letter": "M", "color": "#590761"},
    "Frie Grønne": {"name": "Frie Grønne", "letter": "Q", "color": "#e8ccc7"},
    "Danmarksdemokraterne": {"name": "Danmarksdemokraterne", "letter": "Æ", "color": "#003d7f"},
    "Alternativet": {"name": "Alternativet", "letter": "Å", "color": "#00D564"},
    "Veganerpartiet": {"name": "Veganerpartiet", "letter": "G", "color": "#6da043"},
    "Stram Kurs": {"name": "Stram Kurs", "letter": "P", "color": "#000000"},
    "Klaus Riskær Pedersen": {"name": "Klaus Riskær Pedersen", "letter": "E", "color": "#1F9FAC"},
    "Minoritetspartiet": {"name": "Minoritetspartiet", "letter": "M", "color": "#447d1c"},
    "Centrum-Demokraterne": {"name": "Centrum-Demokraterne", "letter": "D", "color": "#861d7b"},
    "Fremskridtspartiet": {"name": "Fremskridtspartiet", "letter": "Z", "color": "#FFFF00"},
}
